/* Master of Disaster · Smart task search + live UI fixes */
(function () {
'use strict';
window.__modDevVersion={version:'V436',date:'21.08.2026',time:'09:28'};
const norm=v=>String(v||'').trim().replace(/\s+/g,' ').toLocaleLowerCase('de-DE');
const time=i=>{for(const v of [i.completedAt,i.abortedAt,i.completedDate,i.startedAt]){const n=v?new Date(v).getTime():NaN;if(Number.isFinite(n))return n;}return 0;};
const typeName=t=>t==='leisure'?'FREIZEIT':t==='selfrunner'?'SELBSTLÄUFER':t==='cooking'?'KOCHEN':'ARBEIT';
function categoryName(item){if(!item||item.category==null||item.category==='')return 'OHNE KATEGORIE';const id=String(item.category);if(typeof categories!=='undefined'&&Array.isArray(categories)){const c=categories.find(x=>x&&(String(x.id)===id||norm(x.name)===norm(id)));if(c&&c.name)return String(c.name);}return String(item.categoryName||item.category||'OHNE KATEGORIE');}
function collect(){const groups=new Map();function add(item,source){if(!item||!item.text)return;const name=String(item.text).trim().replace(/\s+/g,' ');if(!name)return;const key=norm(name);let g=groups.get(key);if(!g){g={key,name,count:0,activeCount:0,latest:null,latestMs:-1};groups.set(key,g);}g.count++;if(source==='AKTIV'&&!['completed','aborted'].includes(item.status))g.activeCount++;const ms=time(item);if(!g.latest||ms>=g.latestMs){g.latest=item;g.latestMs=ms;g.name=name;}}(Array.isArray(tasks)?tasks:[]).forEach(i=>add(i,'AKTIV'));(Array.isArray(archive)?archive:[]).forEach(i=>add(i,'ARCHIV'));return [...groups.values()];}
function score(g,q){const n=g.key;if(!q)return g.latestMs?1e13-g.latestMs:1e13;if(n===q)return 0;if(n.startsWith(q))return 100;if(n.split(' ').some(w=>w.startsWith(q)))return 200;const i=n.indexOf(q);return i>=0?300+i:Infinity;}
window.getKnownTaskSuggestions=function(query){const q=norm(query);return collect().map(g=>({...g,rank:score(g,q)})).filter(g=>Number.isFinite(g.rank)).sort((a,b)=>a.rank-b.rank||b.latestMs-a.latestMs||a.name.localeCompare(b.name,'de-DE')).slice(0,6).map(g=>({name:g.name,source:g.activeCount?'BEREITS VORHANDEN':'VERLAUF',activeCount:g.activeCount,count:g.count,item:g.latest,latestMs:g.latestMs}));};
window.selectTaskSuggestion=function(encodedName){const name=decodeURIComponent(encodedName),input=document.getElementById('taskInput');if(!input)return;const g=collect().find(x=>x.key===norm(name));input.value=g?g.name:name;if(g&&g.latest){const item=g.latest;if(typeof setNewTaskType==='function')setNewTaskType(item.type||'work');window.__modPendingSuggestionCategory=Object.prototype.hasOwnProperty.call(item,'category')?(item.category==null?null:item.category):null;if(typeof updateNewOptions==='function')updateNewOptions();}if(typeof hideTaskSuggestions==='function')hideTaskSuggestions();input.focus();};
const originalAddTask=window.addTask;if(typeof originalAddTask==='function'){window.addTask=function(){const input=document.getElementById('taskInput'),wanted=input?norm(input.value):'',before=new Set((Array.isArray(tasks)?tasks:[]).map(i=>i&&i.id)),pending=window.__modPendingSuggestionCategory,result=originalAddTask.apply(this,arguments);if(wanted&&pending!==undefined&&Array.isArray(tasks)){const created=[...tasks].reverse().find(i=>i&&!before.has(i.id)&&norm(i.text)===wanted);if(created){created.category=pending;if(typeof saveTasks==='function')saveTasks();if(typeof render==='function')render();}}window.__modPendingSuggestionCategory=undefined;return result;};}
window.renderTaskSuggestions=function(){const input=document.getElementById('taskInput'),box=document.getElementById('taskSuggestions');if(!input||!box)return;const list=window.getKnownTaskSuggestions(input.value);if(!list.length){if(typeof hideTaskSuggestions==='function')hideTaskSuggestions();return;}box.innerHTML=list.map(s=>{const t=s.item||{},meta=[typeName(t.type),categoryName(t)].join(' · '),history=s.count>1?` · ${s.count}×`:'',warning=s.activeCount?'<span class="task-suggestion-active">BEREITS OFFEN</span>':'';return `<button type="button" class="task-suggestion smart-task-suggestion" onmousedown="event.preventDefault()" onclick="selectTaskSuggestion('${encodeURIComponent(s.name)}')"><span class="task-suggestion-main"><span class="task-suggestion-name">${typeof escapeHtml==='function'?escapeHtml(s.name):s.name}</span>${warning}</span><span class="task-suggestion-meta">${meta}${history}</span></button>`;}).join('');box.classList.add('visible');};
const input=document.getElementById('taskInput');if(input){input.addEventListener('input',function(event){event.stopImmediatePropagation();window.renderTaskSuggestions();},true);input.addEventListener('focus',window.renderTaskSuggestions);}

const CATEGORY_STORAGE_KEY='masterOfDisasterCategoriesV405';
function esc(v){return typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function liveCategories(){const seen=new Map();try{const raw=JSON.parse(localStorage.getItem(CATEGORY_STORAGE_KEY)||'[]');(Array.isArray(raw)?raw:[]).forEach(c=>{const clean=String(c||'').trim().replace(/\s+/g,' ');if(clean)seen.set(norm(clean),clean);});}catch(_){};[...(Array.isArray(tasks)?tasks:[]),...(Array.isArray(archive)?archive:[])].forEach(row=>{const clean=String(row&&row.category||'').trim().replace(/\s+/g,' ');if(clean&&!seen.has(norm(clean)))seen.set(norm(clean),clean);});return [...seen.values()].sort((a,b)=>a.localeCompare(b,'de'));}
function optionHtml(current,includeAll){const cur=norm(current);return `${includeAll?'<option value="all">ALLE KATEGORIEN</option>':''}<option value="">OHNE KATEGORIE</option>`+liveCategories().map(c=>`<option value="${esc(c)}" ${norm(c)===cur?'selected':''}>${esc(c.toUpperCase())}</option>`).join('');}
function refreshCategorySelect(select,includeAll=false){if(!select)return;const current=select.value||'';const next=optionHtml(current,includeAll);if(select.innerHTML!==next){select.innerHTML=next;if([...select.options].some(o=>o.value===current))select.value=current;}}
function refreshCategoryUiV433(){refreshCategorySelect(document.getElementById('newCategoryV412'),false);refreshCategorySelect(document.getElementById('editCategoryV412'),false);refreshCategorySelect(document.getElementById('archiveCategoryV412'),false);refreshCategorySelect(document.getElementById('categoryFilterV412'),true);}

function clearPlaceholder(el){if(!el)return;const raw=(el.textContent||'').trim();if(/^[⬜□◻◽]$/.test(raw)){el.textContent='';el.classList.remove('mono-status-v416');}}
function removeOpenStatusPlaceholdersV434(){document.querySelectorAll('#viewContainer .task:not(.archive-task) .status-symbol').forEach(clearPlaceholder);document.querySelectorAll('#viewContainer .next-task-status').forEach(clearPlaceholder);}
function postRenderV434(){refreshCategoryUiV433();removeOpenStatusPlaceholdersV434();}
const previousRenderV434=window.render;if(typeof previousRenderV434==='function'){window.render=function(){const result=previousRenderV434.apply(this,arguments);setTimeout(postRenderV434,0);return result;};}
window.__modV433={version:'V433',refreshCategoryUi:refreshCategoryUiV433};
window.__modV434={version:'V434',removeOpenStatusPlaceholders:removeOpenStatusPlaceholdersV434};
setTimeout(postRenderV434,0);

const style=document.createElement('style');style.textContent='.smart-task-suggestion{display:flex!important;flex-direction:column;align-items:stretch!important;gap:4px;padding:10px 12px!important;text-align:left}.task-suggestion-main{display:flex;align-items:center;gap:8px;min-width:0}.smart-task-suggestion .task-suggestion-name{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.task-suggestion-meta{font-size:10px;letter-spacing:.06em;opacity:.68}.task-suggestion-active{flex:0 0 auto;font-size:9px;letter-spacing:.06em;border:1px solid currentColor;border-radius:999px;padding:2px 5px;opacity:.9}';document.head.appendChild(style);
})();
