const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {chromium} = require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright' : 'playwright');
const root = path.resolve(__dirname, '..');
const foodSource = fs.readFileSync(path.join(root,'food-v544.js'),'utf8');
assert(foodSource.includes("const VERSION='V639'"));
assert(foodSource.includes('saveInventoryStorage'));
assert(foodSource.includes('food-cloud-warning-v548'));
assert(foodSource.includes('getDataSources'));
assert(foodSource.includes('addRecipeModal'));
assert(foodSource.includes("data-food-add-recipe"));
assert(foodSource.includes("food_recipe_ingredients"));
assert(foodSource.includes("NON_SHOPPING_INGREDIENTS=new Set(['wasser','leitungswasser'])"));
assert(foodSource.includes("inventoryQuantityInUnit"));
assert(foodSource.includes("freshShoppingLeadDays"));
assert(foodSource.includes("food_shopping_cart_state"));
assert(foodSource.includes("shoppingCartButton"));
assert(foodSource.includes("toggleShoppingCart"));
(async()=>{
  const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
  try {
    for(const width of [320,390,768]){
      const page = await browser.newPage({viewport:{width,height:844}});
      await page.setContent('<html><body><div id="appFixedTopV475"><header class="header"><h1 class="mod-brand-title-v525">MASTER OF DISASTER</h1></header></div><main class="app"></main></body></html>');
      for(const file of ['app.css','ui.css','app-hub-simple-header-v523.css','food-v544.css'])await page.addStyleTag({content:fs.readFileSync(path.join(root,file),'utf8')});
      await page.addScriptTag({content:fs.readFileSync(path.join(root,'food-v544.js'),'utf8')});
      await page.evaluate(()=>window.__modFoodV544.open());
      await page.locator('.food-meal-card-v544').first().waitFor();
      assert.equal(await page.locator('.food-cloud-warning-v548').count(),1);
      assert.equal((await page.evaluate(()=>window.__modFoodV544.getDataSources().meals)),'fallback');
      assert.equal(await page.locator('#appFixedTopV475').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(238, 243, 232)');
      assert.equal(await page.locator('.food-section-head-v544>div>span').count(),0);
      const arcs=await page.locator('.food-meal-card-v544').evaluateAll(cards=>cards.map(c=>Array.from(c.querySelectorAll('.food-arc-v545'),a=>a.getAttribute('style'))));
      assert(arcs.every(a=>a.length>=1&&a.length<=3));
      const hero=await page.locator('.food-hero-v544').evaluate(el=>getComputedStyle(el,'::after').cssText+getComputedStyle(el,'::after').width);
      assert.equal(await page.locator('.food-hero-v544 .food-arc-v545').count(),0);
      await page.click('[data-food-tab="inventory"]');
      await page.locator('[data-food-storage]').first().click();
      assert.equal(await page.locator('select[name="priority"] option').count(),3);
      assert.equal((await page.locator('.food-modal-head-v544 h3').textContent()).trim(),'Zustand & Verwendung');
      assert.deepEqual(await page.locator('select[name="opened"] option').allTextContents(),['Unangebrochen','Angebrochen']);
      await page.click('[data-food-modal-close]');
      await page.click('[data-food-tab="today"]');
      assert.deepEqual(await page.locator('.food-meal-card-v544').evaluateAll(cards=>cards.map(c=>Array.from(c.querySelectorAll('.food-arc-v545'),a=>a.getAttribute('style')))),arcs);
      assert.equal(await page.locator('.food-meal-card-v544').first().evaluate(el=>getComputedStyle(el).backgroundImage.includes('radial-gradient')),true);
      assert.notEqual(await page.locator('#appFixedTopV475 .header h1').evaluate(el=>getComputedStyle(el).transform),'none');
      await page.click('[data-food-tab="shopping"]');
      assert.equal(await page.locator('[data-shopping-edit]').count(),0);
      assert.equal(await page.locator('[data-shopping-delete]').count(),0);
      assert.equal(await page.locator('.food-shopping-group-v638').count()>0,true);
      assert.equal(await page.locator('[data-food-cart-toggle]').count()>0,true);
      const cartButton=page.locator('[data-food-cart-toggle]').first();
      assert.equal(await cartButton.getAttribute('aria-pressed'),'false');
      const cartStyle=await cartButton.evaluate(el=>({position:getComputedStyle(el).position,right:getComputedStyle(el).right,bottom:getComputedStyle(el).bottom}));
      assert.equal(cartStyle.position,'absolute');
      assert.equal(cartStyle.right,'10px');
      assert.equal(cartStyle.bottom,'9px');
      await page.click('[data-food-tab="recipes"]');
      assert.equal(await page.locator('.food-recipe-card-v544').first().locator('[data-food-rate-recipe]').count(),5);
      assert.equal((await page.locator('.food-recipe-card-v544').first().locator('.food-recipe-rating-v636>span').textContent()).trim(),'Unbewertet');
      assert.equal(await page.locator('[data-food-clear-rating]').count(),0);
      await page.locator('[data-food-add-recipe]').click();
      assert.equal((await page.locator('.food-modal-head-v544 h3').textContent()).trim(),'Rezept hinzufügen');
      assert.equal(await page.locator('[data-food-recipe-row]').count(),1);
      assert.equal(await page.locator('[data-food-recipe-name]').count(),1);
      await page.locator('[data-food-recipe-add-ingredient]').click();
      assert.equal(await page.locator('[data-food-recipe-row]').count(),2);
      await page.locator('[data-food-recipe-remove]').last().click();
      assert.equal(await page.locator('[data-food-recipe-row]').count(),1);
      await page.click('[data-food-modal-close]');
      await page.locator('[data-food-schedule]').first().click();
      const geometry=await page.locator('input[type="date"]').evaluate(el=>({width:el.getBoundingClientRect().width,right:el.getBoundingClientRect().right,font:getComputedStyle(el).fontSize}));
      assert(geometry.right<=width,JSON.stringify({width,geometry}));
      assert.equal(geometry.font,'16px');
      assert.equal(await page.locator('input[type="date"]').evaluate(el=>getComputedStyle(el).fontWeight),'400');
      assert.equal(await page.locator('button[type="submit"]').evaluate(el=>getComputedStyle(el).justifyContent),'flex-start');
      assert.equal(await page.locator('button[type="submit"]').evaluate(el=>getComputedStyle(el).fontWeight),'800');
      await page.click('[data-food-modal-close]');
      await page.evaluate(()=>{window.__modFoodV544.close();window.__modFoodV544.open()});
      await page.click('[data-food-tab="today"]');
      assert.notDeepEqual(await page.locator('.food-meal-card-v544').evaluateAll(cards=>cards.map(c=>Array.from(c.querySelectorAll('.food-arc-v545'),a=>a.getAttribute('style')))),arcs);
      assert.equal(await page.locator('.food-hero-v544').evaluate(el=>getComputedStyle(el,'::after').cssText+getComputedStyle(el,'::after').width),hero);
      await page.evaluate(()=>window.__modFoodV544.close());
      assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('mod-food-v544')),false);
      await page.close();
      console.log('PASS FOOD at '+width+'px: scoped shell, arcs, tabs, storage, date modal');
    }
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
